dist: xenial
sudo: true
#cache:
#  - directories:
#      - /var/lib/docker
#env:
#  global:
#    - DOCKER_SERVER_HOST=docker.local
#    - DOCKER_PROJECT_PATH=components/base
#    - TEST_CONFIG="phpunit.xml.dist"

install:
  - make build
  - make composer-install

script:
  - make lint
  - make static-analysis
  - make coding-standards
  - make tests-unit
  - git log $(git describe --abbrev=0 --tags)...HEAD --no-merges --pretty=format:"* [%h](http://github.com/${TRAVIS_REPO_SLUG}/commit/%H) %s (%cN)"

after_success:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - travis_retry php php-coveralls.phar -v --config .coveralls.yml -v;
