version: "3.7"

services:
  php:
    container_name: ${ADGBASE_COMPOSE_PROJECT_NAME}_php
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    build:
      context: .docker/php7.2-dev
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ../:/packages:rw
    working_dir: /packages/Base
